name: internet_connection_checker_service
description: A service for checking internet connection status and accessibility
homepage: https://github.com/logandx/internet_connection_checker_service
version: 1.0.2

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  connectivity_plus: ^4.0.2
  dio: ^5.3.2
